<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PigeonWatch.BusinessLogic</RootNamespace>
    <AssemblyName>PigeonWatch.BusinessLogic</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\PigeonWatch.Data.csproj" />
    <ProjectReference Include="..\BusinessObjects\PigeonWatch.BusinessObjects.csproj" />
  </ItemGroup>

</Project>
