<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PigeonWatch.BusinessObjects</RootNamespace>
    <AssemblyName>PigeonWatch.BusinessObjects</AssemblyName>
  </PropertyGroup>

</Project>
